### ISSUE TITLE
macでmakeできない

### ISSUE THREAD

**Issue by tortuepin** [nocotan/chppl-tool#14]
clang: warning: -lboost_filesystem: 'linker' input unused
In file included from chppl.cpp:2:
In file included from ./../include/chppl.h:6:
./../include/common_pg.h:6:10: fatal error: 'libpq-fe.h' file not found
# include "libpq-fe.h"

```
     ^
```

1 error generated.
make: **\* [obj/chppl.o] Error 1

**Comment by tortuepin** [comment]
`INCLUDE  = -I /usr/local/pgsql/include/ -I /usr/local/pgsql/include/server/ -I $(shell pg_config --include    dir) -I $(shell pg_config --includedir-server)`

makefile書き換えた

結果

> gcc -o ../bin/chppl obj/chppl.o obj/common_pg.o obj/error.o obj/operation.o obj/validate.o -L /usr/local/pgsql/lib/ -lpq -lcrypt -lstdc++ -g -std=c++11 -lboost_filesystem
> ld: warning: directory not found for option '-L/usr/local/pgsql/lib/'
> ld: library not found for -lcrypt
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: **\* [../bin/chppl] Error 1

もうムリ

**Comment by nocotan** [comment]
-lcrypt外してみた時も頼む

**Comment by nocotan** [comment]
http://stackoverflow.com/questions/12884229/gcc-lcrypt-flag-error-in-unix-c-undefined-reference-to-crypt
これとか

**Comment by tortuepin** [comment]
> gcc -o ../bin/chppl obj/chppl.o obj/common_pg.o obj/error.o obj/operation.o obj/validate.o -L /usr/local/pgsql/lib/ -lpq -lstdc++ -g -std=c++11 -lboost_filesystem
> ld: warning: directory not found for option '-L/usr/local/pgsql/lib/'
> ld: library not found for -lboost_filesystem
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: **\* [../bin/chppl] Error 1

**Comment by tortuepin** [comment]
-lboost_filesystemと、-L/usr/local/pgsql/libを消したら一応できた

実行結果

> bash-3.2$ chppl
> wrong number of arguments.

**Comment by nocotan** [comment]
やったあ
その状態のmakefileでプルリクｐｌｚ

**Comment by tortuepin** [comment]
どうでしょ

**Comment by nocotan** [comment]
大丈夫そうなのでマージした
